jekyll:
  # image specifically for GitHub pages
  image: jekyll/jekyll:pages
  # --future will show future-dated posts
  command: jekyll serve --watch --future
  # map port in container to local port
  ports:
    - 4000:4000
  # map local files (.) to jekyll root in container
  volumes:
    - .:/srv/jekyll
